from enum import Enum

class ConnEvent(Enum):
    CREATEROOM = "CREATEROOM"
    DISCONNECT = "DISCONNECT"
    IDENTIFY = "IDENTIFY"
    HELP = "HELP"
    INVITE = "INVITE"
    JOINROOM = "JOINROOM"
    MESSAGE = "MESSAGE"
    PUBLICMESSAGE = "PUBLICMESSAGE"
    ROOMMESSAGE = "ROOMESSAGE"
    STATUS = "STATUS"
    USERS = "USERS"
